export const CABIN_CLASS = {
  ECONOMY: "ECONOMY",
  PREMIUM_ECONOMY: "PREMIUM ECONOMY",
  BUSINESS: "BUSINESS",
  FIRST: "FIRST",
};

export const SEARCH_FLIGHT_TYPE = {
  ONE_WAY: "One Way",
  RETURN: "Return",
};

export const DOCUMENT_TYPE = {
  PASSPORT: "PASSPORT",
  VISA: "VISA",
  IDENTITY_CARD: "IDENTITY CARD",
  KNOWN_TRAVELER: "KNOWN TRAVELER",
  REDRESS: "REDRESS",
};

export const GENDER_TYPE = {
  MALE: "MALE",
  FEMALE: "FEMALE",
  UNSPECIFIED: "UNSPECIFIED",
  UNDISCLOSED: "UNDISCLOSED",
};

export const DISCOUNT_SUB_TYPE = {
  SPANISH_RESIDENT: "SPANISH RESIDENT",
  AIR_FRANCE_DOMESTIC: "AIR FRANCE DOMESTIC",
  AIR_FRANCE_COMBINED: "AIR FRANCE COMBINED",
  AIR_FRANCE_METROPOLITAN: "AIR FRANCE METROPOLITAN",
};

export const TRAVELER_TYPE = {
  SPANISH_CITIZEN: "SPANISH CITIZEN",
  EUROPEAN_CITIZEN: "EUROPEAN CITIZEN",
  GOVERNMENT_WORKER: "GOVERNMENT WORKER",
  MILITARY: "MILITARY",
  MINOR_WITHOUT_ID: "MINOR WITHOUT ID",
};

export const CONTACT_PURPOSE_TYPE = {
  STANDARD: "STANDARD",
  INVOICE: "INVOICE",
  STANDARD_WITHOUT_TRANSMISSION: "STANDARD WITHOUT TRANSMISSION",
};

export const TICKETING_AGREEMENT_OPTION_TYPE = {
  CONFIRM: "CONFIRM",
  DELAY_TO_QUEUE: "DELAY TO QUEUE",
  DELAY_TO_CANCEL: "DELAY TO CANCEL",
};
