export const PAGE_PATH = {
  SIGNIN: "/signin/",
  SIGNUP: "/signup/",
  RESET_PASSWORD: "/resetPassword/",
  HOME: "/home/",
  PROFILE: "/profile/",
  BOOK: "/book/",
  PLAN: "/plan/",
  JOURNAL: "/journal/",
  JOURNAL_PACK: "/journal/pack/",
  JOURNAL_BUCKET_LIST: "/journal/bucketList/",
  TRAVEL_BUDGET: "/travelBudget/",
  BOOK: "/book/",
  BOOK_FLIGHTS: "/book/flights",
  BOOK_HOTELS: "/book/hotels/",
  BOOK_HOTELS_CONFIRMATION: "/book/hotels/bookingConfirmation/",
  // TODO: Implement below routes..
  BOOKINGS: "/bookings/",
  BOOKINGS_FLIGHTS: "/bookings/flights/",
  BOOKINGS_HOTELS: "/bookings/hotels/",
  CHAT: "/chat/",
  CALENDAR: "/calendar/",
  SETTINGS: "/settings/",
};

export const SIDEBAR_NAVIGATIONS = [
  { label: "Home", value: PAGE_PATH.HOME },
  { label: "Book", value: PAGE_PATH.BOOK },
  { label: "Plan", value: PAGE_PATH.PLAN },
  { label: "Journal", value: PAGE_PATH.JOURNAL },
  { label: "Chat", value: PAGE_PATH.CHAT },
  { label: "Calendar", value: PAGE_PATH.CALENDAR },
  { label: "Travel Budget", value: PAGE_PATH.TRAVEL_BUDGET },
  { label: "Settings", value: PAGE_PATH.SETTINGS },
];
