// -- HOTELS -- //
export const ADD_DESTINATION_DETAILS_FOR_HOTEL =
  "ADD_DESTINATION_DETAILS_FOR_HOTEL";
export const UPDATE_SELECTED_HOTEL = "UPDATE_SELECTED_HOTEL";
export const GET_HOTEL_BOOKINGS = "GET_HOTEL_BOOKINGS";
export const ADD_HOTEL_BOOKING = "ADD_HOTEL_BOOKING";

// -- FLIGHTS -- //
export const ADD_FROM_DETAILS_FOR_FLIGHT = "ADD_FROM_DETAILS_FOR_FLIGHT";
export const ADD_TO_DETAILS_FOR_FLIGHT = "ADD_TO_DETAILS_FOR_FLIGHT";
export const UPDATE_SELECTED_FLIGHT_OFFER = "UPDATE_SELECTED_FLIGHT_OFFER";
export const GET_FLIGHT_BOOKINGS = "GET_FLIGHT_BOOKINGS";
export const ADD_FLIGHT_BOOKING = "ADD_FLIGHT_BOOKING";
