// -- DESTINATION DETAILS -- //
export const ADD_DESTINATION_DETAILS = "ADD_DESTINATION_DETAILS";

// -- HOTELS -- //
export const UPDATE_SELECTED_HOTEL = "UPDATE_SELECTED_HOTEL";
export const GET_HOTEL_BOOKINGS = "GET_HOTEL_BOOKINGS";
export const ADD_HOTEL_BOOKING = "ADD_HOTEL_BOOKING";
