export const ADD_ITEM = "ADD_ITEM";

// -- PACK -- //
export const GET_PACK_ITEMS = "GET_PACK_ITEMS";
export const ADD_PACK_SECTION = "ADD_PACK_SECTION";
export const UPDATE_PACK_SECTION = "UPDATE_PACK_SECTION";
export const DELETE_PACK_SECTION = "DELETE_PACK_SECTION";
export const ADD_PACK_ITEM = "ADD_PACK_ITEM";
export const UPDATE_PACK_ITEM = "UPDATE_PACK_ITEM";
export const DELETE_PACK_ITEM = "DELETE_PACK_ITEM";

// -- BUCKET LIST -- //
export const GET_BUCKET_LIST_ITEMS = "GET_BUCKET_LIST_ITEMS";
export const ADD_BUCKET_LIST_SECTION = "ADD_BUCKET_LIST_SECTION";
export const UPDATE_BUCKET_LIST_SECTION = "UPDATE_BUCKET_LIST_SECTION";
export const DELETE_BUCKET_LIST_SECTION = "DELETE_BUCKET_LIST_SECTION";
export const ADD_BUCKET_LIST_ITEM = "ADD_BUCKET_LIST_ITEM";
export const UPDATE_BUCKET_LIST_ITEM = "UPDATE_BUCKET_LIST_ITEM";
export const DELETE_BUCKET_LIST_ITEM = "DELETE_BUCKET_LIST_ITEM";
